apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  labels:
    app: bar
    ipp-class: "class1"
spec:
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
        ipp-class: "class1"
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
